name: tangle
description: Tangle markdown with mqsoh/knot
inputs:
  volume:
    description: Location of code
    required: true
    default: ./
  working-directory:
    description: The subdirectory you want this to run in
    required: false
outputs:
  time:
    description: This is a temporary value to confirm if it is required
runs:
  using: docker
  image: mqsoh/knot
  args:
    - --volume ${{inputs.volume}}
    - ${{inputs.working_directory}}
