name: Rust Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/rust
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: get deps
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: rustfmt
      uses: LoliGothick/rustfmt-check@v0.4.1
      with:
        toolchain: stable
        options: --manifest-path=./src/rust/Cargo.toml
        working-directory: ./src/rust
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
