name: Rust Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/rust
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: format
      uses: mbrobbel/rustfmt-check@master
      working-directory: ./src/rust
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
